import Head from "next/head";
import Image from "next/image";
import { Suspense } from "react";
import dynamic from "next/dynamic";

export default function Home() {
  const Map = dynamic(() => import("./map/mapComponent"), { ssr: false });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Map />
      </main>
    </div>
  );
}
